# Application constants

MAX_FILE_SIZE_MB = 500
MAX_FILE_SIZE_BYTES = MAX_FILE_SIZE_MB * 1024 * 1024

SUPPORTED_UPLOAD_FORMATS = [".csv", ".xlsx", ".xls", ".json", ".parquet"]

MAX_AGENT_STEPS = 5
MAX_QUERY_ROWS = 10_000
MAX_LLM_CONTEXT_ROWS = 100

DEFAULT_PAGE_SIZE = 50
MAX_PAGE_SIZE = 500

ALLOWED_SQL_STATEMENTS = {"SELECT", "WITH"}
